exports.data = [
  "Let's make this simple, how about I let you-haul me back to your place?",
  "I grew out my undercut, but I could still get under you.",
  "I don’t have a Subaru, but I can be a sub for you.",
  "I don’t usually wear makeup, but I think that lipstick you’re wearing would look great on me.",
  "I hope you know CPR, because you just took my breath away!",
  "Your eyes are like the ocean; I could swim in them all day.",
  "I ought to complain to Spotify for you not being named this week’s hottest single.",
  "When I look in your eyes, I see a very kind soul.",
  "Are you a parking ticket? ‘Cause you’ve got ‘fine’ written all over you.",
  "I never believed in love at first sight, but that was before I saw you.",
  "I didn’t know what I wanted in a woman until I saw you.",
  "If you were a vegetable, you’d be a ‘cute-cumber.’",
  "No wonder the sky is gray (or dark, if at night)—all the color is in your eyes.",
  "You’ve got everything I’ve been searching for, and believe me—I’ve been looking a long time.",
  "You’re like a fine wine. The more of you I drink in, the better I feel.",
  "You’ve got a lot of beautiful curves, but your smile is absolutely my favorite.",
  "Are you as beautiful on the inside as you are on the outside?",
  "If being sexy was a crime, you’d be guilty as charged.",
  "I was wondering if you’re an artist because you were so good at drawing me in.",
  "It says in the Bible to only think about what’s pure and lovely… So I’ve been thinking about you all day long.",
  "I’d like to take you to the movies, but they don’t let you bring in your own snacks.",
  "Do you have a map? I just got lost in your eyes.",
  "You know what you would look really beautiful in? My arms.",
  "I would never play hide and seek with you because someone like you is impossible to find.",
  "Are you a magician? It’s the strangest thing, but every time I look at you, everyone else disappears.",
  "I think there’s something wrong with my phone. Could you try calling it to see if it works?",
  "Hi, I just wanted to thank you for the gift. (pause) I’ve been wearing this smile ever since you gave it to me.",
  "Are you an electrician? Because you’re definitely lighting up my day/night!",
  "I’ve heard it said that kissing is the ‘language of love.’ Would you care to have a conversation with me about it sometime?",
  "I believe in following my dreams. Can I have your Instagram?",
  "I always thought happiness started with an ‘h,’ but it turns out mine starts with ‘u.’",
  "Do you know what the Little Mermaid and I have in common? We both want to be part of your world.",
  "If you were a song, you’d be the best track on the album.",
  "You know, I always thought that Disneyland was the ‘happiest place on Earth,’ but that was before I got a chance to stand here next to you.",
  "On a scale of 1 to America, how free are you tonight?",
  "Want to go outside and get some fresh air with me? You just took my breath away.",
  "If you were a taser, you’d be set to ‘stun.’",
  "If you were a Transformer, you’d be ‘Optimus Fine.’",
  "Is your name Google? Because you have everything I’m searching for.",
  "You know, they say that love is when you don’t want to sleep because reality is better than your dreams. And after seeing you, I don’t think I ever want to sleep again.",
  "Do you ever get tired from running through my thoughts all night?",
  "Your hand looks heavy—can I hold it for you?",
  "Are you a time traveler? Because I absolutely see you in my future.",
  "Do you know what my shirt is made of? Boyfriend material.",
  "I thought this was a (bar/restaurant/etc.), but I must be in a museum because you’re a piece of art.",
  "You know, your smile has been lighting up the room all night and I just had to come and say hello.",
  "Hi, I’m (your name). Do you remember me? Oh, that’s right—we’ve only met in my dreams.",
  "What does it feel like to be the most gorgeous girl in the room?",
  "I can’t tell if that was an earthquake, or if you just seriously rocked my world.",
  "I just had to tell you, your beauty made me truly appreciate being able to see.",
  "If you were a fruit, you’d be a ‘fine-apple.’",
  "I don’t know your name, but I’m sure it’s as beautiful as you are. I’m (your name).",
  "You are astoundingly gorgeous, but I can tell that’s the least interesting thing about you. I’d love to know more.",
  "The sparkle in your eyes is so bright, the sun must be jealous.",
  "One night I looked up at the stars and thought, ‘Wow, how beautiful.’ But now that I’m looking at you, nothing else can compare.",
  "If I had a nickel for every time I saw someone as beautiful as you, I’d still only have five cents.",
  "I think the only way you could possibly be more beautiful is if I got to know you.",
  "If beauty were time, you’d be eternity.",
  "I swear someone stole the stars from the sky and put them in your eyes.",
  "I don’t know which is prettier today—the weather, or your eyes.",
  "In my opinion, there are three kinds of beautiful: Cute, pretty, and sexy. Somehow, you manage to be all three.",
  "I’m not usually religious, but when I saw you, I knew you were the answer to my prayers.",
  "(Hold out your hand) Hey, I’m going for a walk. Would you mind holding this for me?",
  "Do you believe in love at first sight, or should I try walking by again?",
  "I’m really glad I just bought life insurance, because when I saw you, my heart stopped.",
  "Do you happen to have a Band-Aid? ‘Cause I scraped my knees falling for you.",
  "Would you mind giving me a pinch? You’re so cute, I must be dreaming.",
  "Excuse me, do you have the time? I just want to remember the exact minute I got a crush on you.",
  "Wow, when God made you, he was seriously showing off.",
  "Kiss me if I’m wrong but, dinosaurs still exist, right?",
  "If I were a cat, I’d spend all nine of my lives with you.",
  "I was wondering if you could tell me: If you’re here, who’s running Heaven?",
  "So, aside from taking my breath away, what do you do for a living?",
  "When I text you goodnight later, what phone number should I use?",
  "I’m not currently an organ donor, but I’d be happy to give you my heart.",
  "I was going to say something really sweet about you, but when I saw you, I became speechless.",
  "ou know, I believe that honesty is the best policy, so to be perfectly honest, you’re the sexiest man I’ve ever seen.",
  "I’d say, ‘God bless you,’ but it looks like he already did.",
  "There must be something wrong with my eyes—I can’t seem to take them off of you.",
  "You must be a hell of a thief, because you managed to steal my heart from across the room.",
  "If you let me borrow a kiss, I promise I’ll give it right back.",
  "My friends bet me I couldn’t talk to the prettiest girl in the bar. Want to use their money to buy some drinks?",
  "Trust me, I’m not drunk; I’m just intoxicated by you.",
  "I seem to have lost my number—can I have yours?",
  "I was just trying to buy a drink here, but you’re very distracting.",
  "I started reading/watching an interesting book/show last week, and I’d love to discuss it with someone. Have you heard of it?",
  "I was going to call you beautiful, but then I realized I don’t have your number yet.",
  "You see my friend over there? S/he wants to know if you think I’m cute.",
  "You: Are you good at math?Them: No (or Yes)You: Me neither (or Me too). But the only number I care about is yours.",
  "I’m surprised the restaurant/bar/etc. hasn’t asked you to leave yet. You’re so beautiful you’re making all the other girls look bad.",
  "Excuse me, I don’t mean to intrude, but you owe me a drink (pause), because when I saw you, I dropped mine.",
  "Are you any good at boxing? Because you look like a knockout.",
  "I wish I’d paid more attention to science in high school, because you and I’ve got chemistry and I want to know all about it.",
  "It’s never easy meeting a complete stranger—especially one as beautiful as you—without being properly introduced. But can we try anyway?",
  "Do I know you? (pause) Oh, sorry, it’s just that you look just like my next girlfriend.",
  "If I were to ask you out on a date, would your answer be the same as the answer to this question?",
  "Hi, my name is (your name), but you can call me tonight or tomorrow.",
  "Hey, do you mind if we take a picture together? I just want to show my mom what my next girlfriend looks like.",
  "You look like you know how to have a good time. Been on any adventures lately?",
  "You know, I’m actually terrible at flirting. How about you try to pick me up instead?",
  " Do you have a name, or can I just call you ‘mine?’",
  " I’m not sure what it is yet, but something about you seems really interesting.",
  "You know, I had a pickup line ready to go, but you’re so hot it just left my mind.",
  "I’m not photographer, but I can definitely picture us together.",
  "I saw you walking by and I had to come say hello. I love your style. My name’s (your name).",
]